### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by AliAnsari777** [viralvaghela/Jwiki#3]
Hello,
I used your program and I liked it very much, it is very helpful and easy to extend and use.
When I was using your application I faced a problem, when you pass a parameter to constructor to search in Wikipedia and there is no information about that topic program will throw a null pointer exception. I just tried to solve it by adding an "**if**" condition before creating the "**JSONObject**" for retrieving the image and check if the "**displayTitle**" is not null then try to create the "**JSONObject**" and retrieve the image otherwise just give them a value like "information not found".
Now if I pass a parameter that it doesn't have any return value your code will not return a null pointer exception.
I just wanted to let you know, please check this issue and if what I did isn't correct or if it will cause a confliction in other parts, let me know.
Thank you

**Comment by viralvaghela** [comment]
Hi, yes your are right there was a little bug, whatever you did will work fine,Thanks.
