### ISSUE TITLE
Can You Add this project to Maven?

### ISSUE THREAD

**Issue by arshcoder777** [viralvaghela/Jwiki#4]
Hi @viralveghela I love this project and its really useful to me. But it will be if you add it to maven . then users can access it using maven without downloading them directly. Also can you Javadoc this so that there is a documentation.

**Comment by viralvaghela** [comment]
Hi @javas-apps , thank you so much. Yes I will try to upload it on maven as soon as possible.

**Comment by arshcoder777** [comment]
Ok Sir Thanks.
